### ISSUE TITLE
RFCs Web Page [mdbook]

### ISSUE THREAD

**Issue by mordamax** [polkadot-fellows/RFCs#53]
@PierreBesson suggested rendering our polkadot-fellows/RFCs as a webpage - similar to https://eips.ethereum.org/

- Could be made by markdown book https://rust-lang.github.io/mdBook/index.html
- Can either integrated into RFC's repo or in https://github.com/paritytech/rfc-book
- Do we want to put this page behind subdomain, like https://rfc.polkadot.network? 

Tracked in https://github.com/paritytech/eng-automation/issues/1

**Comment by rzadp** [comment]
I have created the mdbook and I'm looking for feedback.

The book can be previewed [here](https://paritytech.github.io/RFCs/).

Calling thumb-uppers: @xlc @lrazovic @davxy @bkchr

**Comment by xlc** [comment]
I can't say I enjoy the font and colour scheme but otherwise looks good
<img width="800" alt="Screenshot 2023-12-04 at 1 08 58 PM" src="https://github.com/polkadot-fellows/RFCs/assets/1201310/3edf33a9-1922-4313-b175-961ed23b7cad">

**Comment by rzadp** [comment]
Thanks for the feedback. :)

## Update

- I have toned down the Polkadot branded theme.
- I'm generating TOCs.
- I've separated proposed RFCs into "new", "stale", and the rest
  - Currently "new" means PRs created in the last 7 days, and "stale" means PRs not updated for at least 30 days.

Please take another [look](https://paritytech.github.io/RFCs/).
